Sell Tickets
ArmaanT/downtown-marketplace pull request #17
Opened 2019-05-06 17:56 UTC by Pwpon500

This PR:
- Finishes the project babyyyyy

2019-05-06 22:29 UTC, ArmaanT requested changes

2019-05-06 22:29 UTC, ArmaanT commented on main/templates/main/base.html
> +          <a href="/accounts/profile/{{ user.username }}" class="button is-primary">Profile</a>
Don't hardcode this, you can use reverse and then add the actual username at the end

2019-05-06 22:29 UTC, ArmaanT commented on main/urls.py
> +from main import views
For consistency's sake, it's better to import the actual views instead of views as a whole

2019-05-06 22:29 UTC, ArmaanT commented on main/templates/main/downtown.html
> +function getCookie(name) {
It may be worth putting this in the base template since we refer to it multiple times

2019-05-06 22:29 UTC, ArmaanT commented on main/migrations/0007_ticket_sold.py
> +# Generated by Django 2.2 on 2019-05-06 17:08
You should merge this and the previous migration file

2019-05-07 01:30 UTC, Pwpon500 commented on main/templates/main/base.html
> +          <a href="/accounts/profile/{{ user.username }}" class="button is-primary">Profile</a>
Thank you Armaan. Very cool!

2019-05-07 01:30 UTC, Pwpon500 commented on main/urls.py
> +from main import views
What a great point. Implemented.

2019-05-07 01:31 UTC, Pwpon500 commented on main/migrations/0007_ticket_sold.py
> +# Generated by Django 2.2 on 2019-05-06 17:08
Wow I didn't think of that. Done.

2019-05-07 01:31 UTC, Pwpon500 commented on main/templates/main/downtown.html
> +function getCookie(name) {
You are truly a smart guy. Implemented.

2019-05-07 01:47 UTC, ArmaanT approved these changes

2019-05-07 01:58 UTC, merged